/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.aplikasiAR;
import model.komponenAplikasi;
import model.perbandinganMedia;
import model.promosiProperti;

/**
 *
 * @author User
 */
public class FrameApp extends javax.swing.JFrame {
         // Array untuk menyimpan admin
    private static final ArrayList<aplikasiAR> arList = new ArrayList<>();
    private static final ArrayList<komponenAplikasi> komponenList = new ArrayList<>();
    private static final ArrayList<perbandinganMedia> bandingList = new ArrayList<>();
    private static final ArrayList<promosiProperti> promosiList = new ArrayList<>();

    /**
     * Creates new form FrameApp
     */
    public FrameApp() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        pnlAplikasi = new javax.swing.JPanel();
        txtVersi = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtPlatform = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtNmAplikasi = new javax.swing.JTextField();
        btnInputAplikasi = new javax.swing.JButton();
        txtFitur = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtPengembang = new javax.swing.JTextField();
        pnlKomponen = new javax.swing.JPanel();
        txtFungsi = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnInputKomponen = new javax.swing.JButton();
        txtNmKomponen = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        pnlBanding = new javax.swing.JPanel();
        txtAspek = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnInputBanding = new javax.swing.JButton();
        txtTradisional = new javax.swing.JTextField();
        txtAr = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtKesimpulan = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        pnlPromosi = new javax.swing.JPanel();
        txtIdPromosi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnInputPromosi = new javax.swing.JButton();
        txtNmProperti = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtJnsPromosi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTarget = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtDurasi = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtBiaya = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        btnAplikasi = new javax.swing.JButton();
        btnKomponen = new javax.swing.JButton();
        btnBanding = new javax.swing.JButton();
        btnPromosi = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Content.setBackground(new java.awt.Color(153, 204, 255));
        Content.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(204, 204, 204));
        pnlHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Content.add(pnlHome, "card6");

        pnlAplikasi.setBackground(new java.awt.Color(204, 204, 204));
        pnlAplikasi.setForeground(new java.awt.Color(255, 255, 255));
        pnlAplikasi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtVersi.setBackground(new java.awt.Color(255, 255, 255));
        txtVersi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVersiActionPerformed(evt);
            }
        });
        pnlAplikasi.add(txtVersi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 260, 30));

        jLabel13.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Nama Aplikasi");
        pnlAplikasi.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel14.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Versi");
        pnlAplikasi.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 215, -1));

        txtPlatform.setBackground(new java.awt.Color(255, 255, 255));
        pnlAplikasi.add(txtPlatform, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 260, 30));

        jLabel18.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Platform");
        pnlAplikasi.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel19.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("FItur Utama");
        pnlAplikasi.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 190, -1));

        txtNmAplikasi.setBackground(new java.awt.Color(255, 255, 255));
        txtNmAplikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNmAplikasiActionPerformed(evt);
            }
        });
        pnlAplikasi.add(txtNmAplikasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 260, 30));

        btnInputAplikasi.setText("INPUT");
        btnInputAplikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputAplikasiActionPerformed(evt);
            }
        });
        pnlAplikasi.add(btnInputAplikasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 91, 41));

        txtFitur.setBackground(new java.awt.Color(255, 255, 255));
        pnlAplikasi.add(txtFitur, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 260, 30));

        jLabel20.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Pengembang");
        pnlAplikasi.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 190, -1));

        txtPengembang.setBackground(new java.awt.Color(255, 255, 255));
        pnlAplikasi.add(txtPengembang, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 260, 30));

        Content.add(pnlAplikasi, "card3");

        pnlKomponen.setBackground(new java.awt.Color(204, 204, 204));
        pnlKomponen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFungsi.setBackground(new java.awt.Color(255, 255, 255));
        txtFungsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFungsiActionPerformed(evt);
            }
        });
        pnlKomponen.add(txtFungsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 258, 30));

        jLabel15.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Fungsi");
        pnlKomponen.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        btnInputKomponen.setText("INPUT");
        btnInputKomponen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputKomponenActionPerformed(evt);
            }
        });
        pnlKomponen.add(btnInputKomponen, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 91, 41));

        txtNmKomponen.setBackground(new java.awt.Color(255, 255, 255));
        txtNmKomponen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNmKomponenActionPerformed(evt);
            }
        });
        pnlKomponen.add(txtNmKomponen, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 258, 30));

        jLabel17.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Nama Komponen");
        pnlKomponen.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        Content.add(pnlKomponen, "card4");

        pnlBanding.setBackground(new java.awt.Color(204, 204, 204));
        pnlBanding.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAspek.setBackground(new java.awt.Color(255, 255, 255));
        pnlBanding.add(txtAspek, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 260, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Aspek");
        pnlBanding.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 180, -1));

        btnInputBanding.setText("INPUT");
        btnInputBanding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputBandingActionPerformed(evt);
            }
        });
        pnlBanding.add(btnInputBanding, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 91, 41));

        txtTradisional.setBackground(new java.awt.Color(255, 255, 255));
        pnlBanding.add(txtTradisional, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 260, 30));

        txtAr.setBackground(new java.awt.Color(255, 255, 255));
        pnlBanding.add(txtAr, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 260, 30));

        jLabel21.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Nilai Tradisional");
        pnlBanding.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel22.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Nilai AR");
        pnlBanding.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 150, -1));

        txtKesimpulan.setBackground(new java.awt.Color(255, 255, 255));
        pnlBanding.add(txtKesimpulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 260, 30));

        jLabel23.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Kesimpulan");
        pnlBanding.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 150, -1));

        Content.add(pnlBanding, "card5");

        pnlPromosi.setBackground(new java.awt.Color(204, 204, 204));
        pnlPromosi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIdPromosi.setBackground(new java.awt.Color(255, 255, 255));
        pnlPromosi.add(txtIdPromosi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 260, 30));

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Id Promosi");
        pnlPromosi.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 167, -1));

        btnInputPromosi.setText("INPUT");
        btnInputPromosi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputPromosiActionPerformed(evt);
            }
        });
        pnlPromosi.add(btnInputPromosi, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 91, 41));

        txtNmProperti.setBackground(new java.awt.Color(255, 255, 255));
        pnlPromosi.add(txtNmProperti, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 260, 30));

        jLabel24.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Nama Properti");
        pnlPromosi.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        txtJnsPromosi.setBackground(new java.awt.Color(255, 255, 255));
        pnlPromosi.add(txtJnsPromosi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 260, 30));

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Jenis Promosi");
        pnlPromosi.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 180, -1));

        txtTarget.setBackground(new java.awt.Color(255, 255, 255));
        pnlPromosi.add(txtTarget, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 260, 30));

        jLabel25.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Target Audiens");
        pnlPromosi.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        txtDurasi.setBackground(new java.awt.Color(255, 255, 255));
        pnlPromosi.add(txtDurasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 260, 30));

        jLabel26.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Durasi Promosi");
        pnlPromosi.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        txtBiaya.setBackground(new java.awt.Color(255, 255, 255));
        pnlPromosi.add(txtBiaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 260, 30));

        jLabel27.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Biaya Promosi");
        pnlPromosi.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        Content.add(pnlPromosi, "card2");

        getContentPane().add(Content, java.awt.BorderLayout.CENTER);

        Header.setBackground(new java.awt.Color(0, 0, 0));
        Header.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Form Input Data Promosi Properti");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Menu.setBackground(new java.awt.Color(51, 51, 51));
        Menu.setForeground(new java.awt.Color(51, 51, 51));

        btnAplikasi.setBackground(new java.awt.Color(204, 204, 204));
        btnAplikasi.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnAplikasi.setForeground(new java.awt.Color(0, 0, 0));
        btnAplikasi.setText("APLIKASI AR");
        btnAplikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplikasiActionPerformed(evt);
            }
        });

        btnKomponen.setBackground(new java.awt.Color(204, 204, 204));
        btnKomponen.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnKomponen.setForeground(new java.awt.Color(0, 0, 0));
        btnKomponen.setText("KOMPONEN APLIKASI");
        btnKomponen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKomponenActionPerformed(evt);
            }
        });

        btnBanding.setBackground(new java.awt.Color(204, 204, 204));
        btnBanding.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnBanding.setForeground(new java.awt.Color(0, 0, 0));
        btnBanding.setText("PERBANDINGAN MEDIA");
        btnBanding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBandingActionPerformed(evt);
            }
        });

        btnPromosi.setBackground(new java.awt.Color(204, 204, 204));
        btnPromosi.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnPromosi.setForeground(new java.awt.Color(0, 0, 0));
        btnPromosi.setText("PROMOSI PROPERTI");
        btnPromosi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromosiActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(204, 204, 204));
        btnHome.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 0, 0));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKomponen)
                    .addComponent(btnBanding)
                    .addComponent(btnPromosi)
                    .addComponent(btnAplikasi, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAplikasi, btnBanding, btnKomponen, btnPromosi});

        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAplikasi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKomponen)
                .addGap(18, 18, 18)
                .addComponent(btnBanding)
                .addGap(18, 18, 18)
                .addComponent(btnPromosi)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAplikasi, btnBanding, btnKomponen, btnPromosi});

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInputPromosiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputPromosiActionPerformed
        try {
            promosiProperti objPromosi = new promosiProperti();
            objPromosi.setIdPromosi(txtIdPromosi.getText());
            objPromosi.setNamaPromosi(txtNmProperti.getText());
            objPromosi.setJenisPromosi(txtJnsPromosi.getText());
            objPromosi.setTargetAudiens(txtTarget.getText());
            objPromosi.setBiayaPromosi(Integer.parseInt(txtBiaya.getText()));
            objPromosi.setDurasiPromosi(txtDurasi.getText());
            objPromosi.infoPromosiPropertiPopup();
            // Menambahkan objek ke dalam ArrayList
            promosiList.add(objPromosi);

            // Memberi konfirmasi bahwa penjualan berhasil ditambahkan
            JOptionPane.showMessageDialog(null, 
                "Promosi berhasil ditambahkan!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);

            // Menampilkan semua penjualan yang ada di ArrayList
            StringBuilder allPromosi = new StringBuilder("Daftar Promosi:\n");
            for (promosiProperti Promosi : promosiList) {
                allPromosi.append("ID Promosi: ").append(Promosi.getIdPromosi())
                          .append("\n Nama Properti: ").append(Promosi.getNamaPromosi())
                          .append("\n Jenis Promosi: ").append(Promosi.getJenisPromosi())
                          .append("\n Target Audiens: ").append(Promosi.getTargetAudiens())
                          .append("\n Biaya Promosi: ").append(Promosi.getBiayaPromosi())
                          .append("\n Durasi Promosi: ").append(Promosi.getDurasiPromosi())
                          .append("\n\n");
            }

            JOptionPane.showMessageDialog(null, allPromosi.toString(), 
                "Daftar Promosi", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, 
            "Biaya harus berupa angka!", 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, 
                "Terjadi kesalahan: " + ex.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInputPromosiActionPerformed

    private void btnInputBandingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputBandingActionPerformed
        try {
            perbandinganMedia objbanding = new perbandinganMedia();
            objbanding.setAspek(txtAspek.getText());
            objbanding.setNilaiTradisional(txtTradisional.getText());
            objbanding.setNilaiAR(txtAr.getText());
            objbanding.setKesimpulan(txtKesimpulan.getText());
            objbanding.infoPerbandinganMediaPopup();
            // Menambahkan objek ke dalam ArrayList
            bandingList.add(objbanding);

            // Memberi konfirmasi bahwa perbandingan berhasil ditambahkan
            JOptionPane.showMessageDialog(null, 
                "Perbandingan berhasil ditambahkan!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);

            // Menampilkan semua perbandingan yang ada di ArrayList
            StringBuilder allBanding = new StringBuilder("Daftar Perbandingan:\n");
            for (perbandinganMedia banding : bandingList) {
                allBanding.append("Aspek: ").append(banding.getAspek())
                        .append("\n Nilai Tradisional: ").append(banding.getNilaiTradisional())
                        .append("\n Nilai AR: ").append(banding.getNilaiAR())
                        .append("\n Kesimpulan: ").append(banding.getKesimpulan())
                        .append("\n\n");
            }

            JOptionPane.showMessageDialog(null, allBanding.toString(), 
                "Daftar Perbandingan", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, 
                "Terjadi kesalahan: " + ex.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInputBandingActionPerformed

    private void btnInputKomponenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputKomponenActionPerformed
            try {
                komponenAplikasi objKomponen = new komponenAplikasi();
                objKomponen.setNamaKomponen(txtNmKomponen.getText());
                objKomponen.setFungsi(txtFungsi.getText());
                objKomponen.infoKomponenAplikasiPopup();
                // Menambahkan objek ke dalam ArrayList
                komponenList.add(objKomponen);

            // Memberi konfirmasi bahwa komponen berhasil ditambahkan
            JOptionPane.showMessageDialog(null, 
                "Komponen berhasil ditambahkan!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);

            // Menampilkan semua komponen yang ada di ArrayList
            StringBuilder allKomponen = new StringBuilder("Daftar Komponen:\n");
            for (komponenAplikasi kategori : komponenList) {
                allKomponen.append("Nama Komponen : ").append(kategori.getNamaKomponen())
                        .append("\n Fungsi : ").append(kategori.getFungsi())
                        .append("\n\n");
            }

            JOptionPane.showMessageDialog(null, allKomponen.toString(), 
                "Daftar Komponen", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, 
                "Terjadi kesalahan: " + ex.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInputKomponenActionPerformed

    private void btnAplikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplikasiActionPerformed
        Content.removeAll(); 
        Content.add(pnlAplikasi);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnAplikasiActionPerformed

    private void btnKomponenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKomponenActionPerformed
        Content.removeAll(); 
        Content.add(pnlKomponen);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnKomponenActionPerformed

    private void btnBandingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBandingActionPerformed
        Content.removeAll(); 
        Content.add(pnlBanding);
        Content.repaint();
        Content.revalidate();        
    }//GEN-LAST:event_btnBandingActionPerformed

    private void btnPromosiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromosiActionPerformed
        Content.removeAll(); 
        Content.add(pnlPromosi);
        Content.repaint();
        Content.revalidate();        
    }//GEN-LAST:event_btnPromosiActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        Content.removeAll(); 
        Content.add(pnlHome);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnHomeActionPerformed

    private void txtVersiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVersiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVersiActionPerformed

    private void txtNmAplikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNmAplikasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNmAplikasiActionPerformed

    private void btnInputAplikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputAplikasiActionPerformed
        try {
            aplikasiAR objAplikasi = new aplikasiAR();
            objAplikasi.setNamaAplikasi(txtNmAplikasi.getText());
            objAplikasi.setVersi(txtVersi.getText());
            objAplikasi.setPlatform(txtPlatform.getText());
            objAplikasi.setFiturUtama(txtFitur.getText());
            objAplikasi.setPengembang(txtPengembang.getText());
            objAplikasi.infoAplikasiARPopup();
            // Menambahkan objek ke dalam ArrayList
            arList.add(objAplikasi);

            // Memberi konfirmasi bahwa aplikasi berhasil ditambahkan
            JOptionPane.showMessageDialog(null, 
                "Aplikasi berhasil ditambahkan!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);

            // Menampilkan semua aplikasi yang ada di ArrayList
            StringBuilder allAplikasi = new StringBuilder("Daftar Aplikasi:\n");
            for (aplikasiAR aplikasi : arList) {
                allAplikasi.append("Nama Aplikasi : ").append(aplikasi.getNamaAplikasi())
                        .append("\n Versi : ").append(aplikasi.getVersi())
                        .append("\n Platform : ").append(aplikasi.getPlatform())
                        .append("\n Fitur Utama : ").append(aplikasi.getFiturUtama())
                        .append("\n Pengembang : ").append(aplikasi.getPengembang())
                        .append("\n\n");
            }

            JOptionPane.showMessageDialog(null, allAplikasi.toString(), 
                "Daftar Aplikasi", JOptionPane.INFORMATION_MESSAGE);
        
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, 
                "Terjadi kesalahan: " + ex.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInputAplikasiActionPerformed

    private void txtFungsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFungsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFungsiActionPerformed

    private void txtNmKomponenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNmKomponenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNmKomponenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton btnAplikasi;
    private javax.swing.JButton btnBanding;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInputAplikasi;
    private javax.swing.JButton btnInputBanding;
    private javax.swing.JButton btnInputKomponen;
    private javax.swing.JButton btnInputPromosi;
    private javax.swing.JButton btnKomponen;
    private javax.swing.JButton btnPromosi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel pnlAplikasi;
    private javax.swing.JPanel pnlBanding;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlKomponen;
    private javax.swing.JPanel pnlPromosi;
    private javax.swing.JTextField txtAr;
    private javax.swing.JTextField txtAspek;
    private javax.swing.JTextField txtBiaya;
    private javax.swing.JTextField txtDurasi;
    private javax.swing.JTextField txtFitur;
    private javax.swing.JTextField txtFungsi;
    private javax.swing.JTextField txtIdPromosi;
    private javax.swing.JTextField txtJnsPromosi;
    private javax.swing.JTextField txtKesimpulan;
    private javax.swing.JTextField txtNmAplikasi;
    private javax.swing.JTextField txtNmKomponen;
    private javax.swing.JTextField txtNmProperti;
    private javax.swing.JTextField txtPengembang;
    private javax.swing.JTextField txtPlatform;
    private javax.swing.JTextField txtTarget;
    private javax.swing.JTextField txtTradisional;
    private javax.swing.JTextField txtVersi;
    // End of variables declaration//GEN-END:variables
}
